import turtle

def drawClock():
    #turtle.hideturtle()
    turtle.penup()
    turtle.goto(0,0)
    turtle.pendown()
    turtle.circle(100)
    turtle.penup()
    turtle.goto(0,5)
    turtle.write(("6"),False)
    turtle.penup()
    turtle.goto(90,100)
    turtle.write(("3"),False)
    turtle.penup()
    turtle.goto(0,185)
    turtle.write(("12"),False)
    turtle.penup()
    turtle.goto(-90,100)
    turtle.write(("9"),False)
    turtle.penup()
    turtle.goto(0,100)
    turtle.pendown()
    turtle.goto(80,105)
    turtle.penup()
    turtle.goto(0,100)
    turtle.pendown()
    turtle.goto(-50,120)
    turtle.penup()
    turtle.goto(-15,-20)
    turtle.write(("9:15:00"),False)

drawClock()

